// <auto-generated />
namespace AdAtTheRightTime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class postmergewithjoeFri : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postmergewithjoeFri));
        
        string IMigrationMetadata.Id
        {
            get { return "201606241437436_post merge with joe Fri"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
